// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using COOPSAPI;
//
//    var tidalPrediction = TidalPrediction.FromJson(jsonString);

namespace COOPSAPI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TidalPrediction
    {
        [JsonProperty("predictions")]
        public List<Prediction> Predictions { get; set; }
    }

    public partial class Prediction
    {
        [JsonProperty("t")]
        public string T { get; set; }

        [JsonProperty("v")]
        public string V { get; set; }
    }

    public partial class TidalPrediction
    {
        public static TidalPrediction FromJson(string json) => JsonConvert.DeserializeObject<TidalPrediction>(json, COOPSAPI.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this TidalPrediction self) => JsonConvert.SerializeObject(self, COOPSAPI.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}